import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#000000',
    alignItems: 'center',
    paddingVertical: 40,
  },
  topImageContainer: {
    width: '100%',
    height: 380, 
    position: 'relative',
    marginBottom: 10,
  },
  imgTopLeft: {
    position: 'absolute',
    top: -20,
    left: -20,
    width: 140,
    height: 100,
    borderRadius: 20,
  },
  imgMidLeft: {
    position: 'absolute',
    top: 140,
    left: -40,
    width: 150,
    height: 180,
    borderRadius: 20,
  },
  imgCenter: {
    position: 'absolute',
    top: 40,
    alignSelf: 'center', 
    width: 180,
    height: 250,
    borderRadius: 20,
    zIndex: 2, 
  },
  imgMidRight: {
    position: 'absolute',
    top: 110,
    right: 30,
    width: 90,
    height: 130,
    borderRadius: 20,
    zIndex: 1,
  },
  imgBottomRight: {
    position: 'absolute',
    top: 270,
    right: -10,
    width: 120,
    height: 110,
    borderRadius: 20,
  },
  logoContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  logoP: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
  },
  headerText: {
    color: '#FFFFFF',
    fontSize: ,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  textInput: {
    width: '90%',
    height: 50,
    borderWidth: 1,
    borderColor: '#AAAAAA',
    borderRadius: 25,
    paddingLeft: 20,
    color: '#FFFFFF',
    backgroundColor: '#111111',
    marginBottom: 15,
  },
  textInputFocused: {
    borderColor: '#E60023',
  },
  textInputPlaceholder: {
    color: '#AAAAAA',
  },
  buttonRed: {
    width: '90%',
    height: 50,
    backgroundColor: '#E60023',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  buttonRedText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonBlack: {
    width: '90%',
    height: 50,
    backgroundColor: '#000000',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#AAAAAA',
  },
  buttonBlackText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  googleLogo: {
    width: 25,
    height: 25,
    marginRight: 10,
    resizeMode: 'contain',
  },
  bottomTextContainer: {
    width: '90%',
    alignItems: 'center',
  },
  facebookText: {
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 20,
    fontSize: 14,
  },
  linkTextRed: {
    fontWeight: 'bold',
  },
  legalText: {
    color: '#AAAAAA',
    textAlign: 'center',
    fontSize: 11,
    lineHeight: 16,
  },
  linkText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});