import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    alignItems: 'center',
    paddingTop: 10, 
    paddingBottom: 15,
  },
  topImageContainer: {
    width: '100%',
    height: 320,
    position: 'relative',
    marginTop: 10,
    marginBottom: 5,
  },
  imgTopLeft: {
    position: 'absolute',
    top: 0, 
    left: -10,
    width: 120,
    height: 90,
    borderRadius: 20,
  },
  imgMidLeft: {
    position: 'absolute',
    top: 110,
    left: -30,
    width: 130,
    height: 160,
    borderRadius: 20,
  },
  imgCenter: {
    position: 'absolute',
    top: 40,
    alignSelf: 'center',
    width: 160,
    height: 220,
    borderRadius: 20,
    zIndex: 2,
  },
  imgMidRight: {
    position: 'absolute',
    top: 80,
    right: 15,
    width: 90,
    height: 120,
    borderRadius: 20,
    zIndex: 1,
  },
  imgBottomRight: {
    position: 'absolute',
    top: 220,
    right: -10,
    width: 100,
    height: 100,
    borderRadius: 20,
  },
  logoContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  logoP: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
  },
  headerText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  textInput: {
    width: '90%',
    height: 48,
    borderWidth: 1,
    borderColor: '#AAAAAA',
    borderRadius: 25,
    paddingLeft: 20,
    color: '#FFFFFF',
    backgroundColor: '#111111',
    marginBottom: 12,
  },
  textInputFocused: {
    borderColor: '#E60023',
  },
  textInputPlaceholder: {
    color: '#AAAAAA',
  },
  buttonRed: {
    width: '90%',
    height: 50,
    backgroundColor: '#E60023',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  buttonRedText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonBlack: {
    width: '90%',
    height: 50,
    backgroundColor: '#000000',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#AAAAAA',
  },
  buttonBlackText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  googleLogo: {
    width: 25,
    height: 25,
    marginRight: 10,
    resizeMode: 'contain',
  },
  bottomTextContainer: {
    width: '90%',
    alignItems: 'center',
  },
  facebookText: {
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 20,
    fontSize: 14,
  },
  linkTextRed: {
    fontWeight: 'bold',
  },
  legalText: {
    color: '#AAAAAA',
    textAlign: 'center',
    fontSize: 11,
    lineHeight: 16,
  },
  linkText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});